- .dockerignore
- .travis.yml
- Dockerfile
- config.json.example
- lib/bootstrap/config.js
- package.json
The trusty tag was removed from npm's Docker repository, the current
Dockerfile doesn't work anymore
Use the current LTS instead (4.6.0)
> Fix the Dockerfile

- package-lock.json
- routes/base.js
Fixes sockethub/sockethub#237
Removing the file broke existing apps linking to it.
> Re-add unminified activity-streams.js file

- README.md
Here's an updated description of Sockethub based on a talk with @skddc some time ago, in anticipation of a 3.0 release. Once we get this text fairly clear and straightforward, I'll update the website and wiki with similar language. @skddc @galfert I would appreciate your feedback.
> first draft of updated description

- packages/sockethub-platform-irc/index.js
- packages/sockethub-platform-irc/package.json
- packages/sockethub-platform-irc/yarn.lock
- packages/sockethub/views/examples/irc.ejs
- yarn.lock
This PR uses the Tls irc-socket fix in https://github.com/silverbucket/irc-socket/tree/v4-alpha 
Tested on my local machine and it works at least with both secure and non-secure connection sand send/receiving messages.
> Use irc-socket Tls fix from silverbucket/irc-socket

- README.md
- package.json
Easier to run for devs and makes the command composable.
> Add yarn/npm script for ESLint

- packages/sockethub-platform-xmpp/API.md
- packages/sockethub-platform-xmpp/package.json
- packages/sockethub-platform-xmpp/src/index.js
- packages/sockethub-platform-xmpp/yarn.lock
Updates API.md for new function signatures and removes references to simple-xmpp
> Remove references to simple-xmpp

- .travis.yml
This should do CI integrations on 1. PRs and 2. Merges to master only
> Travis: only do branch update builds on master

- package.json
- packages/sockethub-platform-irc/index.js
- packages/sockethub/src/common.test.ts
- packages/sockethub/src/crypto.test.ts
- packages/sockethub/src/platform-instance.test.ts
- packages/sockethub/src/routes.test.ts
- packages/sockethub/src/store.test.ts
Linting checks weren't being run properly during compliance, fixed it and fixed some linting errors.
> Fix broken linting

- Dockerfile
- docker-compose.yml
~~Not completed yet, need to rewrite the parts that I wrote with yarn still~~
Should be good now
closes #511
> Fix/update Docker setup

- .eslintrc
- package.json
- packages/sockethub/bin/sockethub
- packages/sockethub/src/bootstrap/init.ts
- packages/sockethub/src/platform.ts
- yarn.lock
Resolves https://github.com/sockethub/sockethub/issues/355
> Added linting checks for common node security vectors

- .github/renovate.json
Main change here is that we will now group patch and minor releases in the devDependencies group together into one PR.
> Renovate Config

- packages/sockethub-platform-xmpp/src/index.js
- packages/sockethub-platform-xmpp/src/index.test.js
> Add user-generated ID to outgoing XMPP messages

- package.json
- packages/sockethub-platform-xmpp/src/index.js
- packages/sockethub-platform-xmpp/src/index.test.js
- packages/sockethub-platform-xmpp/src/schema.js
- packages/sockethub-platform-xmpp/src/utils.js
- packages/sockethub-platform-xmpp/src/utils.test.js
- packages/sockethub/views/examples/xmpp.ejs
- test/xmpp.test.js
> Switch to userAddress from username

- packages/sockethub-platform-xmpp/src/utils.js
- packages/sockethub-platform-xmpp/src/utils.test.js
Here's a fix based on https://github.com/xmppjs/xmpp.js/tree/main/packages/client#client-1
> use port as part of service

- packages/sockethub/src/janitor.ts
- packages/sockethub/src/platform-instance.ts
- packages/sockethub/src/serve.ts
This is a bugfix to remove callbacks when a session is terminated.
> Clean up session callbacks properly

- packages/schemas/src/helpers/error-parser.ts
This should finally resolve #726 there was a second check of the same type of approach I totally overlooked.
> Fix property check

- packages/activity-streams.js/src/activity-streams.js
- packages/server/src/middleware/expand-activity-stream.ts
> Option to disable unknown prop warnings

- .github/workflows/compliance.yml
- .github/workflows/integration.yml
- packages/platform-feeds/API.md
- packages/platform-xmpp/src/incoming-handlers.data.js
- packages/platform-xmpp/src/incoming-handlers.js
- packages/schemas/package.json
- packages/schemas/src/helpers/error-parser.ts
- packages/schemas/src/helpers/objects.ts
- packages/schemas/src/index.test.data.streams.ts
- packages/schemas/src/index.test.ts
- packages/schemas/src/schemas/activity-stream.ts
- packages/schemas/src/validator.ts
- packages/schemas/yarn.lock
- packages/server/package.json
- packages/server/yarn.lock
- yarn.lock
Set the `published` property to `ISO 8601`.
Resolves #247
> Use ISO 8601 dates for incoming XMPP messages

- .github/workflows/compliance.yml
- .github/workflows/integration.yml
- Dockerfile
- README.md
- package.json
- packages/client/yarn.lock
- packages/irc2as/yarn.lock
- packages/platform-irc/yarn.lock
- packages/platform-xmpp/yarn.lock
- packages/server/yarn.lock
* Use `postinstall` for `lerna bootstrap`
* Update github actions and docker
* Update docs for a more conventional quick start
> Use `postinstall` for `lerna bootstrap`

- package.json
- pnpm-lock.yaml
Will be required in the future.
> Add lerna-lite publish dependency

- packages/server/package.json
- packages/sockethub/package.json
The live reloading is built-in to bun, so this was a lot easier than expected.
Resolves #890
> Hot reload using `bun run dev`

- bun.lock
- packages/server/package.json
- packages/server/src/sentry.test.ts
> Fix sentry config reading error 
