sockethub/sockethub

package.json
This fixes an npm warning:
```
npm WARN sockethub@1.0.3 license should be a valid SPDX license expression
```
I'm not sure this version is actually what you were going for. So take this as more of a constructive issue report than an actual proposal for this specific license.
If you want to use a different version, here's a list with valid expressions for LGPL:
https://github.com/stdarg/spdx-licenses/blob/master/spdx.json#L527-L556
=> Use valid SPDX license ID

routes/base.js
This is needed for dynamically loading them via Fetch, e.g. in ServiceWorker scripts.
It also serves `socket.io.js` from the same directory root as the other assets, to make it less confusing.
=> Add CORS headers to static assets

views/examples/dummy.ejs
This is causing issues running the dummy example.
=> Missing an ending quotation mark in the dummy example.

package.json
There are already features used in the code, which aren't available by default on versions older than 5. LTS is 6.x and current is 7.7.2, so I think this is a reasonable requirement.
closes #206
=> Require a halfway modern node version

lib/middleware.js
This reverts commit 8e9e72ad4bfc2b692b517b3c173be2f0f41e243c.
I was testing the latest master with Hyperchannel, and Sockethub didn't join me to any channels anymore. There were no apparent error messages in the Sockethub log that I could see. I checked the most recent commits and found this to be the culprit breaking it.
To be honest, I have no clue how it would break anything, because it looks like it should behave the exact same way.
=> Revert "self-call function"

lib/client.js
Log the various connection events by socket.io to better understand what's going on when we drop into various broken connection states.
Reference: https://socket.io/docs/client-api/
Related to issue #213
=> Add socket.io connection state handlers

config.json.example
I found out about the problem while working on the Docker setup (I'll send a PR soon, using Docker Compose)
The config entry for the Redis URL is explained in the README. If you
want comments you need to use YAML or another format that has comments
=> Remove comments from the JSON config: JSON doesn't allow comments

Dockerfile, README.md, docker-compose.yml
I'm considering using Docker Compose to deploy sockethub, so here's a PR. The old Docker setup was using another non-official image and didn't set up Redis (this does it as a separate linked container).
Can someone else give this a try? On this branch `docker-compose up` should give you a working sockethub on http://localhost:10550/
I tested it on my Mac using Docker for Mac and on Ubuntu 16.04 (using official Docker packages)
=> Initial Docker Compose support

package.json
In the `dev` script in package.json I noticed a call to `cdd` at the end. I didn't recognize that commend and found that I don't have such a command (on macOS).
I don't know if it's a custom script or something Linux specific, but I assume it's for changing back to the original directory after the script previously changed into `packages/sockethub`. I replaced it witch `cd -`, which does exactly that, but AFAIK is in the POSIX standard. So it should be available in most shells.
I also added it to the end of the `start` script as well, because that also changes directories.
=> Replace cdd call with cd -

packages/sockethub/bin/sockethub, packages/sockethub/src/sockethub.ts
Closes #271
When the main process exits, either by receiving a TERM or INT signal, or when an unhandled exception occurs, all platform instances are removed. So no child processes are left behind.
=> Remove all platform instances when main process exits

packages/sockethub/src/platform-instance.ts
Fixes #255
When installing Sockethub as a dependency of another project and then trying to run it from there, an error is thrown:
```
Error: Cannot find module '/Users/galfert/code/active/kosmos/hyperchannel/dist/platform.js'
at Function.Module._resolveFilename (internal/modules/cjs/loader.js:1030:15)
at Function.Module._load (internal/modules/cjs/loader.js:899:27)
at Function.executeUserEntryPoint [as runMain] (internal/modules/run_main.js:71:12)
at internal/main/run_main_module.js:17:47 {
code: 'MODULE_NOT_FOUND',
requireStack: []
}
```
This fixes that error.
=> Use relative path for process forking

.travis.yml
travis-ci.org is being deprecated at the end of the year and the PRs were taking sometimes days to be queued (or never). Switched to travis-ci.com and at the same time enabled the new graviton2 platform which they claim is even faster.
https://docs.travis-ci.com/user/migrate/open-source-repository-migration/
https://blog.travis-ci.com/2020-09-11-arm-on-aws
=> Migrate to travis-ci.com and enable graviton2

packages/sockethub/src/config.ts
This is just to ensure that nowhere the config object is being re-initialized within the same thread, as that could be indicative of a larger issue.
=> Ensure config is only loaded once per thread

packages/sockethub/src/js/client.js
Show replay objects played back to server when SockethubClient instances `debug` property is true
=> Add debug logging toggle to SockethubClient

packages/sockethub/src/js/client.js
Not all ActivityStreams objects contain a target. If there is none, then accessing sub properties fails.
Not sure if this is the correct fix, and why that string combines actor and target.
=> Fix client exception when AS object has no target

.eslintrc, packages/sockethub-platform-feeds/index.js, packages/sockethub-platform-irc/index.js, packages/sockethub-platform-xmpp/index.js, packages/sockethub/src/bootstrap/platforms.js, packages/sockethub/src/platform.ts, packages/sockethub/src/sockethub.ts
Currently credentials are passed in to every platform function which were previously used to access the appropriate client instance or re-connect if needed. The architecture has progressively moved away from that to simply destroying and restarting the platform if the connection is lost. This PR adds a `requireCredentials` property to the platform config, which is an array listing every method that needs the credentials object passed in. For now, all functions are defined, but as the client internals of each platform is improved we can slowly remove methods from the list.
Resolves #287
=> New config option to define which platform methods require the credentials option passed in. 

packages/sockethub/src/platform-instance.ts
Fixes #354
This fixes the error "TypeError: Cannot read property 'socket' of undefined", by passing the complete job object instead of just the decrypted message to the job handler.
=> Pass complete job object to handleJobResult method

.github/renovate.json
This config will:
* Not separate by packages within the monorepo for the same dependency update
* Only create PRs during the weekdays (avoid weekend pileups)
* Wait 3 days after a release before creating the PR
* Auto-update branches when behind master
* Will create an Issue which will act as a dashboard (overview) or all of the existing and pending (not created yet) PRs
=> Update renovate config to be less spammy

packages/sockethub-platform-irc/index.js
Fix for what LGTM reported as a polynominal regexp, more info here: https://lgtm.com/rules/1511427506129/
=> Fix polynominal time required to match regexp

.github/workflows/compliance.yml
Removed support for node 15 from compliance checks. ~~Added node 12 as it's still officially supported.~~
=> Remove support for node 15

packages/sockethub-platform-xmpp/src/schema.js
=> XMPP credentials `server` property no longer required

packages/sockethub/src/platform-instance.ts
Only try to parse `resultString` if it's not undefined
=> Safely parse resultString

packages/sockethub-platform-irc/API.md, packages/sockethub-platform-irc/index.js, packages/sockethub-platform-xmpp/API.md, packages/sockethub-platform-xmpp/src/index.js
Found some occurrences of the obsolete `type: 'set'` for credentials objects in the examples.
NB: In the `API.md` files I didn't remove the `@` from the `@type` as well. I think that should be a separate PR that removes all of them in the whole document.
=> Replace old 'set' type with 'credentials' in examples

packages/sockethub-platform-xmpp/src/index.js, packages/sockethub-platform-xmpp/src/index.test.js
As per XEP-0308, and with the same AS object format as incoming corrections are forward to clients.
(Note: the XML fakes are still not tested correctly. I added FIXME comments, but since I wasn't able to drive-by-fix them easily, and they're already broken in master since before I worked on message corrections, I consider the problem out of scope for these feature PRs.)
=> Support outgoing message correction

packages/activity-streams.js/src/activity-streams.d.ts
This is just to help with type warnings from within sockethub, which is now all typescript and includes the activity-streams lib
=> provide d.ts file for activity streams

packages/sockethub-schemas/src/validator.js
It was only being used in one place, and I didn't notice the incompatibility as I'm running node `16.5` locally. This way we can keep node `12` support. Eventually this will be TypeScript so it doesn't matter that we don't use this in the JS.
=> Remove `?.` conditional accessor from JS code

packages/server/views/examples/xmpp.ejs
As a quick short-hand, if you use `an@xmpp.address: a message` in the text input, it uses the data left of the `:` as the target, this fixes the object format.
=> Fix XMPP example - target format

packages/server/src/bootstrap/init.test.ts, packages/server/src/bootstrap/init.ts
There was a bug (that didn't seem to produce any symptoms) where the bootstrap process was being run twice during startup. This fixes the issue and adds some tests.
=> Ensure bootstrap initialization is only run once

packages/activity-streams/package.json, packages/client/package.json, packages/crypto/package.json, packages/data-layer/package.json, packages/examples/package.json, packages/irc2as/package.json, packages/platform-dummy/package.json, packages/platform-feeds/package.json, packages/platform-irc/package.json, packages/platform-xmpp/package.json, packages/schemas/package.json, packages/server/package.json, packages/sockethub/package.json
Renovatebot seems confused, thinking sub-packages are still managed by npm while the root is bun. Setting bun in each package.json to be explicit.
=> Define bun in each package.json

.gitignore, bun.lock, integration/browser.integration.js, package.json, packages/activity-streams/README.md, packages/activity-streams/package.json, packages/activity-streams/src/activity-streams.ts, packages/client/README.md, packages/client/package.json, packages/client/src/sockethub-client.ts, packages/examples/package.json, packages/examples/src/routes/dummy/+page.svelte, packages/platform-dummy/src/index.ts, packages/platform-xmpp/src/index.js, packages/schemas/src/schemas/activity-stream.ts, packages/server/package.json, packages/server/src/bootstrap/init.ts, packages/server/src/config.ts, packages/server/src/defaults.json, packages/server/src/index.ts, packages/server/src/listener.ts, packages/server/src/platform-instance.ts, packages/server/src/platform.ts, packages/server/src/sentry.ts, packages/server/src/sockethub.ts
Added basic sentry support. Only is enabled if a Sentry DNS is supplied (either with a `--sentry.dsn [dsn]` arg, or in the config file.
Resolves #817
=> Add Sentry support

.github/workflows/compliance.yml, .github/workflows/integration.yml, bun.lock
There was a bug in bun 1.2.3 (https://github.com/oven-sh/bun/issues/17601) that caused a regression where the frozen-lockfile param was failing due to changes when using a monorepo, when there were no changes.
The bug was fixed in 1.2.4
This reverts the pinning of the version to 1.2.2 and back to 1.2 (.x)
=> Revert to Bun minor version for github actions runs

.github/renovate.json
Renovate keeps trying to update a ghost pnpm-lock.yml file that no longer exists in the repo since we switched to bun. So for now I'm disabling it.
=> Disable Renovate lockfile maintenance 

packages/platform-irc/src/index.test.ts, packages/platform-irc/src/index.ts, packages/platform-irc/src/schema.ts, packages/platform-xmpp/src/index.js, packages/platform-xmpp/src/index.test.js, packages/platform-xmpp/src/schema.js
Added `disctonnect()` functions for both IRC and XMPP platforms, which calls cleanup and sets `initialized` to `false`, which - when checked with the `janitor` process - will indicate the thread can be destroyed.
=> Add disconnect() function for XMPP and IRC platforms
